filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /opt/myhoneypot/log/glastopf.log

#  document_type: json
#  json.message_key: log

#------------------- Logstash output -----------------------
output.logstash:
  hosts: ["10.0.0.10:5044"]

